### ISSUE TITLE
Hopping with cozy time auction pepe generates failed transaction

### ISSUE THREAD

**Issue by crmn111** [CryptoPepes/cryptopepes-alpha-test#21]
Hopping with cozy time auction pepe generates a warning inside MetaMask, press submit....
<img width="1142" alt="screen shot 2018-06-12 at 15 34 52" src="https://user-images.githubusercontent.com/881181/41293709-5adfe1b2-6e56-11e8-9fa5-930772205969.png">

The the transaction failed:
<img width="502" alt="screen shot 2018-06-12 at 15 40 16" src="https://user-images.githubusercontent.com/881181/41293963-1d45201e-6e57-11e8-9235-028f2a551439.png">

This is the failed transaction on ethercan:
https://ropsten.etherscan.io//tx/0x653aba672f16f132bcf5a830db1b90e20353f71baa57ed3c891c2da1cf1c5f5e

**Comment by programmerror** [comment]
Looks like pepe 99 often had cozy time, so he had probably an active cooldown at the time. The cooldown also didn't update, because the watcher only considered to update the child. This will change once the front-end does some more/better tracking. The backend will also be updated, to update parents after breeding. The visual part is similar to issue #29, which is fixed and being tested now. Next release will include a fix for backend too :+1:
